package("CFSP")
    add_urls("https://github.com/CoralFans-Dev/CFSP.git")
    add_versions("1.0.0", "4b421b80a556bcac19dbb812063cda5f841eeece")
    on_install(function (package)
        import("package.tools.xmake").install(package, configs)
    end)